server:
  port: 8080
spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
    - url: https://300lux.ru/
      name: 300lux
    - url: https://dress-me-up.ru/
      name: dress-me-up
    - url: https://triko.agency/
      name: triko
