indexing-settings:
  sites:
    - url: https://dimonvideo.ru
      name: Dimonvideo
    - url: http://www.playback.ru
      name: Playback
    - url: https://www.svetlovka.ru
      name: Svetlovka
  agents:
    - Searchify
    - Findr
    - Discovera
    - Inquisit
    - TruSearch
    - QuickQuery
  batch_size: 1000
  thread_multiplier: 4

server:
  port: 8080

spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    driver_classname: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true