indexing-settings:
  sites:
    - url: https://nikoartgallery.com
      name: NikoArtGallery
    - url: https://ipfran.ru
      name: Iprfan
    - url: https://www.svetlovka.ru
      name: Svetlovka
    - url: https://triko.agency
      name: Triko
  agents:
    - Searchify
    - Findr
    - Discovera
    - Inquisit
    - TruSearch
    - QuickQuery
  batch_size: 30
  parallelism: 32

server:
  port: 8080

spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true